package entities;
// Generated 17 juin 2019 23:35:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String login;
     private String password;
     private String mail;
     private Set<Category> categories =  new HashSet<Category>(0);

    public User() {
    }

    public User(String login, String password, String mail, Set  categories) {
       this.login = login;
       this.password = password;
       this.mail = mail;
       this.categories = categories;
    }

    public User(String login, String password, String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public User(int parseInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Set  getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set  categories) {
        this.categories = categories;
    }
  public void addCategories(Category categ)
    {
        this.categories.add(categ);
    }
    @Override
    public String toString() {
        return "{\"id\":" + iduser + ", \"login\":\"" + login + "\", \"password\":\"" + password + "\", \"mail\":\"" + mail + "\"}";
    }




}


