package entities;
// Generated 29 avr. 2019 22:52:54 by Hibernate Tools 4.3.1



/**
 * Website generated by hbm2java
 */
public class Website  implements java.io.Serializable {


     private Integer idWebSite;
     private String title;
     private String link;

    public Website() {
    }

    public Website(String title, String link) {
       this.title = title;
       this.link = link;
    }
   
    public Integer getIdWebSite() {
        return this.idWebSite;
    }
    
    public void setIdWebSite(Integer idWebSite) {
        this.idWebSite = idWebSite;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }




}


